workflows:
  expo-ios:
    name: Expo iOS Build
    max_build_duration: 60
    environment:
      node: latest
      expo: latest
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build iOS app
        script: |
          expo build:ios --non-interactive --no-wait
    artifacts:
      - dist/*.ipa
