workflows:
  expo-ios:
    name: Expo iOS Build
    max_build_duration: 60
    environment:
      node: latest
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Login to Expo
        script: |
          npx expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD
      - name: EAS Build for iOS
        script: |
          npx eas build --platform ios --non-interactive --profile production
    artifacts:
      - build/*.ipa
